/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.TelaConferenciaControl;
import control.TelaEscolherArquivoControl;
import javax.swing.JButton;

/**
 *
 * @author William
 */
public class TelaEscolherArquivo extends javax.swing.JFrame {

    TelaEscolherArquivoControl controlArquivo;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaEscolherArquivo() {
        initComponents();
    }

    /**
     * Creates new form TelaPrincipal
     */
    public TelaEscolherArquivo(TelaEscolherArquivoControl controlArquivo) {
        initComponents();
        this.controlArquivo = controlArquivo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLerArquivo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btSelecionarArquivo = new javax.swing.JButton();
        btConferir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventariador Johnmar");

        btLerArquivo.setText("LER");
        btLerArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLerArquivoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Ler Arquivo");

        btSelecionarArquivo.setText("Arquivo");
        btSelecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarArquivoActionPerformed(evt);
            }
        });

        btConferir.setText("Conferir");
        btConferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConferirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btConferir)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSelecionarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                                .addComponent(btLerArquivo)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelecionarArquivo)
                    .addComponent(btLerArquivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btConferir)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLerArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLerArquivoActionPerformed
        // TODO add your handling code here:
//        controlArquivo.lerArquivoAction();
        controlArquivo.lerArquivoPeloExcelAction();
    }//GEN-LAST:event_btLerArquivoActionPerformed

    private void btSelecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarArquivoActionPerformed
        // TODO add your handling code here:
        controlArquivo.acionaAberturaDeArquivo();
    }//GEN-LAST:event_btSelecionarArquivoActionPerformed

    private void btConferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConferirActionPerformed
        // TODO add your handling code here:
        controlArquivo.chamarTelaConferenciaAction();
    }//GEN-LAST:event_btConferirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEscolherArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEscolherArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEscolherArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEscolherArquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEscolherArquivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConferir;
    private javax.swing.JButton btLerArquivo;
    private javax.swing.JButton btSelecionarArquivo;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public JButton getBtConferir() {
        return btConferir;
    }

    public void setBtConferir(JButton btConferir) {
        this.btConferir = btConferir;
    }

    public JButton getBtLerArquivo() {
        return btLerArquivo;
    }

    public void setBtLerArquivo(JButton btLerArquivo) {
        this.btLerArquivo = btLerArquivo;
    }

    public JButton getBtSelecionarArquivo() {
        return btSelecionarArquivo;
    }

    public void setBtSelecionarArquivo(JButton btSelecionarArquivo) {
        this.btSelecionarArquivo = btSelecionarArquivo;
    }

}
